// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = PageTopBlockSlice | ExperienceBlockSlice | IntroTextBlockSlice | ImageGridBlockSlice | SingleImageBlockSlice | WorksGalleryBlockSlice | NewsFeedBlockSlice | MarqueeBlockSlice | BasicTextBlockSlice

/**
 * Content for About documents
 */
interface AboutDocumentData {
	/**
	 * Slice Zone field in *About*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>;/**
	 * SEO Title field in *About*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: about.seoTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoTitle: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *About*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: about.seoDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoDescription: prismic.KeyTextField;
	
	/**
	 * OG Image field in *About*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.ogImage
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ogImage: prismic.ImageField<never>;
	
	/**
	 * OG Title field in *About*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.ogTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogTitle: prismic.KeyTextField;
	
	/**
	 * OG Description field in *About*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.ogDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogDescription: prismic.KeyTextField;
	
	/**
	 * Twitter account field in *About*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.twitterAccount
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	twitterAccount: prismic.ContentRelationshipField<"socialAccount">;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type CaseDocumentDataSlicesSlice = SingleImageBlockSlice | ImageGridBlockSlice | IntroTextBlockSlice | BasicTextBlockSlice | CasePageTopBlockSlice | MarqueeBlockSlice

/**
 * Content for Case documents
 */
interface CaseDocumentData {
	/**
	 * Name field in *Case*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Overview field in *Case*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.overview
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	overview: prismic.KeyTextField;
	
	/**
	 * Cover image field in *Case*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.coverImage
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	coverImage: prismic.ImageField<never>;
	
	/**
	 * Timestamp field in *Case*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.timestamp
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#timestamp
	 */
	timestamp: prismic.TimestampField;
	
	/**
	 * Next case field in *Case*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.nextCase
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	nextCase: prismic.ContentRelationshipField<"case">;
	
	/**
	 * Slice Zone field in *Case*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<CaseDocumentDataSlicesSlice>;/**
	 * SEO Title field in *Case*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.seoTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoTitle: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Case*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.seoDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoDescription: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Case*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.ogImage
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ogImage: prismic.ImageField<never>;
	
	/**
	 * OG Title field in *Case*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.ogTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogTitle: prismic.KeyTextField;
	
	/**
	 * OG Description field in *Case*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.ogDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogDescription: prismic.KeyTextField;
	
	/**
	 * Twitter account field in *Case*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case.twitterAccount
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	twitterAccount: prismic.ContentRelationshipField<"socialAccount">;
}

/**
 * Case document from Prismic
 *
 * - **API ID**: `case`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CaseDocumentData>, "case", Lang>;

type ContactDocumentDataSlicesSlice = ContactsBlockSlice | WorksGalleryBlockSlice

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
	/**
	 * Slice Zone field in *Contact*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>;/**
	 * SEO Title field in *Contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: contact.seoTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoTitle: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: contact.seoDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoDescription: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Contact*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.ogImage
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ogImage: prismic.ImageField<never>;
	
	/**
	 * OG Title field in *Contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.ogTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogTitle: prismic.KeyTextField;
	
	/**
	 * OG Description field in *Contact*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.ogDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogDescription: prismic.KeyTextField;
	
	/**
	 * Twitter account field in *Contact*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.twitterAccount
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	twitterAccount: prismic.ContentRelationshipField<"socialAccount">;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ContactDocumentData>, "contact", Lang>;

/**
 * Content for Contact email documents
 */
interface ContactEmailDocumentData {
	/**
	 * Email address field in *Contact email*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contactEmail.contactEmail
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	contactEmail: prismic.KeyTextField;
}

/**
 * Contact email document from Prismic
 *
 * - **API ID**: `contactEmail`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactEmailDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ContactEmailDocumentData>, "contactEmail", Lang>;

type HomeDocumentDataSlicesSlice = RecentCasesBlockSlice | NewsFeedBlockSlice | MarqueeBlockSlice | HeroBlockSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;/**
	 * SEO Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.seoTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoTitle: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.seoDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoDescription: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.ogImage
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ogImage: prismic.ImageField<never>;
	
	/**
	 * OG Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.ogTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogTitle: prismic.KeyTextField;
	
	/**
	 * OG Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.ogDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogDescription: prismic.KeyTextField;
	
	/**
	 * Twitter account field in *Home*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.twitterAccount
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	twitterAccount: prismic.ContentRelationshipField<"socialAccount">;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *News feed → News*
 */
export interface NewsFeedDocumentDataNewsItem {
	/**
	 * News item field in *News feed → News*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsFeed.news[].newsItem
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	newsItem: prismic.ContentRelationshipField<"newsPost">;
}

/**
 * Content for News feed documents
 */
interface NewsFeedDocumentData {
	/**
	 * News field in *News feed*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsFeed.news[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	news: prismic.GroupField<Simplify<NewsFeedDocumentDataNewsItem>>;
}

/**
 * News feed document from Prismic
 *
 * - **API ID**: `newsFeed`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsFeedDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<NewsFeedDocumentData>, "newsFeed", Lang>;

/**
 * Content for News post documents
 */
interface NewsPostDocumentData {
	/**
	 * Title field in *News post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsPost.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Image field in *News post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsPost.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Source link field in *News post*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsPost.sourceLink
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	sourceLink: prismic.LinkField;
	
	/**
	 * Source name field in *News post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsPost.sourceName
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sourceName: prismic.KeyTextField;
	
	/**
	 * Source type field in *News post*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: telegram
	 * - **API ID Path**: newsPost.sourceType
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	sourceType: prismic.SelectField<"telegram" | "instagram" | "dribbble" | "behance" | "other", "filled">;
	
	/**
	 * Social account field in *News post*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: newsPost.socialAccount
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	socialAccount: prismic.ContentRelationshipField<"socialAccount">;
}

/**
 * News post document from Prismic
 *
 * - **API ID**: `newsPost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<NewsPostDocumentData>, "newsPost", Lang>;

type SiteFooterDocumentDataSlicesSlice = never

/**
 * Content for Site footer documents
 */
interface SiteFooterDocumentData {
	/**
	 * CTA row 1 field in *Site footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteFooter.ctaRow1
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ctaRow1: prismic.KeyTextField;
	
	/**
	 * CTA row 2 field in *Site footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteFooter.ctaRow2
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ctaRow2: prismic.KeyTextField;
	
	/**
	 * CTA Button text field in *Site footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteFooter.ctaButtonText
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ctaButtonText: prismic.KeyTextField;
	
	/**
	 * CTA Button font size field in *Site footer*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteFooter.ctaButtonFontSize
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	ctaButtonFontSize: prismic.NumberField;
	
	/**
	 * CTA Button font size (Safari) field in *Site footer*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteFooter.ctaButtonFontSizeSafari
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	ctaButtonFontSizeSafari: prismic.NumberField;
	
	/**
	 * Slice Zone field in *Site footer*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteFooter.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SiteFooterDocumentDataSlicesSlice>;
}

/**
 * Site footer document from Prismic
 *
 * - **API ID**: `siteFooter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteFooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SiteFooterDocumentData>, "siteFooter", Lang>;

/**
 * Content for Site header documents
 */
interface SiteHeaderDocumentData {
	/**
	 * Left text field in *Site header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteHeader.leftText
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	leftText: prismic.KeyTextField;
	
	/**
	 * Right text field in *Site header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteHeader.rightText
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	rightText: prismic.KeyTextField;
}

/**
 * Site header document from Prismic
 *
 * - **API ID**: `siteHeader`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteHeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SiteHeaderDocumentData>, "siteHeader", Lang>;

/**
 * Content for Site general info documents
 */
interface SiteInformationDocumentData {
	/**
	 * name field in *Site general info*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteInformation.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
}

/**
 * Site general info document from Prismic
 *
 * - **API ID**: `siteInformation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteInformationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SiteInformationDocumentData>, "siteInformation", Lang>;

/**
 * Item in *Site navigation → Nav links*
 */
export interface SiteNavigationDocumentDataNavLinksItem {
	/**
	 * Name field in *Site navigation → Nav links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteNavigation.navLinks[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Alias field in *Site navigation → Nav links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteNavigation.navLinks[].alias
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	alias: prismic.KeyTextField;
	
	/**
	 * Href field in *Site navigation → Nav links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteNavigation.navLinks[].href
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	href: prismic.LinkField;
}

/**
 * Content for Site navigation documents
 */
interface SiteNavigationDocumentData {
	/**
	 * Nav links field in *Site navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: siteNavigation.navLinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	navLinks: prismic.GroupField<Simplify<SiteNavigationDocumentDataNavLinksItem>>;
}

/**
 * Site navigation document from Prismic
 *
 * - **API ID**: `siteNavigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteNavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SiteNavigationDocumentData>, "siteNavigation", Lang>;

/**
 * Content for Social account documents
 */
interface SocialAccountDocumentData {
	/**
	 * Service name field in *Social account*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: socialAccount.serviceName
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	serviceName: prismic.KeyTextField;
	
	/**
	 * Name field in *Social account*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: socialAccount.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Url field in *Social account*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: socialAccount.url
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	url: prismic.LinkField;
	
	/**
	 * Type field in *Social account*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: telegram
	 * - **API ID Path**: socialAccount.type
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	type: prismic.SelectField<"telegram" | "instagram" | "dribbble" | "behance" | "linkedIn" | "twitter", "filled">;
}

/**
 * Social account document from Prismic
 *
 * - **API ID**: `socialAccount`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialAccountDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<SocialAccountDocumentData>, "socialAccount", Lang>;

/**
 * Item in *Social links → Social links*
 */
export interface SocialLinksDocumentDataSocialLinksItem {
	/**
	 * Social account field in *Social links → Social links*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: socialLinks.socialLinks[].socialAccount
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	socialAccount: prismic.ContentRelationshipField<"socialAccount">;
	
	/**
	 * Enabled field in *Social links → Social links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: socialLinks.socialLinks[].enabled
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enabled: prismic.BooleanField;
}

/**
 * Content for Social links documents
 */
interface SocialLinksDocumentData {
	/**
	 * Social links field in *Social links*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: socialLinks.socialLinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	socialLinks: prismic.GroupField<Simplify<SocialLinksDocumentDataSocialLinksItem>>;
}

/**
 * Social links document from Prismic
 *
 * - **API ID**: `socialLinks`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialLinksDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SocialLinksDocumentData>, "socialLinks", Lang>;

type WorkDocumentDataSlicesSlice = PageTopBlockSlice | BasicTextBlockSlice | SingleImageBlockSlice | AllCasesBlockSlice

/**
 * Content for Work documents
 */
interface WorkDocumentData {
	/**
	 * Slice Zone field in *Work*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>;/**
	 * SEO Title field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: work.seoTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoTitle: prismic.KeyTextField;
	
	/**
	 * SEO Description field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: work.seoDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seoDescription: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Work*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.ogImage
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	ogImage: prismic.ImageField<never>;
	
	/**
	 * OG Title field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.ogTitle
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogTitle: prismic.KeyTextField;
	
	/**
	 * OG Description field in *Work*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.ogDescription
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	ogDescription: prismic.KeyTextField;
	
	/**
	 * Twitter account field in *Work*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work.twitterAccount
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	twitterAccount: prismic.ContentRelationshipField<"socialAccount">;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

/**
 * Item in *Works gallery → Images*
 */
export interface WorksGalleryDocumentDataImagesItem {
	/**
	 * Image field in *Works gallery → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: worksGallery.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for Works gallery documents
 */
interface WorksGalleryDocumentData {
	/**
	 * Images field in *Works gallery*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: worksGallery.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<WorksGalleryDocumentDataImagesItem>>;
}

/**
 * Works gallery document from Prismic
 *
 * - **API ID**: `worksGallery`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorksGalleryDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<WorksGalleryDocumentData>, "worksGallery", Lang>;

export type AllDocumentTypes = AboutDocument | CaseDocument | ContactDocument | ContactEmailDocument | HomeDocument | NewsFeedDocument | NewsPostDocument | SiteFooterDocument | SiteHeaderDocument | SiteInformationDocument | SiteNavigationDocument | SocialAccountDocument | SocialLinksDocument | WorkDocument | WorksGalleryDocument;

/**
 * Primary content in *AllCases → Primary*
 */
export interface AllCasesBlockSliceDefaultPrimary {
	/**
	 * Spacing top field in *AllCases → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: all_cases_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *AllCases → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: all_cases_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
}

/**
 * Default variation for AllCases Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllCasesBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<AllCasesBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *AllCases*
 */
type AllCasesBlockSliceVariation = AllCasesBlockSliceDefault

/**
 * AllCases Shared Slice
 *
 * - **API ID**: `all_cases_block`
 * - **Description**: AllCasesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllCasesBlockSlice = prismic.SharedSlice<"all_cases_block", AllCasesBlockSliceVariation>;

/**
 * Primary content in *BasicText → Primary*
 */
export interface BasicTextBlockSliceDefaultPrimary {
	/**
	 * Text field in *BasicText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: basic_text_block.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Large text field in *BasicText → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: basic_text_block.primary.largeText
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	largeText: prismic.BooleanField;
	
	/**
	 * Animate headings (h1, h2, h3) field in *BasicText → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: basic_text_block.primary.animateHeadings
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	animateHeadings: prismic.BooleanField;
	
	/**
	 * Position field in *BasicText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left
	 * - **API ID Path**: basic_text_block.primary.position
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	position: prismic.SelectField<"left" | "right" | "center", "filled">;
	
	/**
	 * Spacing top field in *BasicText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: basic_text_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *BasicText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: basic_text_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
}

/**
 * Default variation for BasicText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BasicTextBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BasicTextBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *BasicText*
 */
type BasicTextBlockSliceVariation = BasicTextBlockSliceDefault

/**
 * BasicText Shared Slice
 *
 * - **API ID**: `basic_text_block`
 * - **Description**: BasicTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BasicTextBlockSlice = prismic.SharedSlice<"basic_text_block", BasicTextBlockSliceVariation>;

/**
 * Primary content in *CasePageTop → Primary*
 */
export interface CasePageTopBlockSliceDefaultPrimary {
	/**
	 * Title field in *CasePageTop → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_page_top_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *CasePageTop → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_page_top_block.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for CasePageTop Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasePageTopBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CasePageTopBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CasePageTop*
 */
type CasePageTopBlockSliceVariation = CasePageTopBlockSliceDefault

/**
 * CasePageTop Shared Slice
 *
 * - **API ID**: `case_page_top_block`
 * - **Description**: CasePageTopBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasePageTopBlockSlice = prismic.SharedSlice<"case_page_top_block", CasePageTopBlockSliceVariation>;

/**
 * Primary content in *Contacts → Primary*
 */
export interface ContactsBlockSliceDefaultPrimary {
	/**
	 * Title field in *Contacts → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Avatar field in *Contacts → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts_block.primary.avatar
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	avatar: prismic.ImageField<never>;
}

/**
 * Default variation for Contacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactsBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Contacts*
 */
type ContactsBlockSliceVariation = ContactsBlockSliceDefault

/**
 * Contacts Shared Slice
 *
 * - **API ID**: `contacts_block`
 * - **Description**: ContactsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsBlockSlice = prismic.SharedSlice<"contacts_block", ContactsBlockSliceVariation>;

/**
 * Primary content in *Experience → Primary*
 */
export interface ExperienceBlockSliceDefaultPrimary {
	/**
	 * Title field in *Experience → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Spacing top field in *Experience → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: experience_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *Experience → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: experience_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
}

/**
 * Primary content in *Experience → Items*
 */
export interface ExperienceBlockSliceDefaultItem {
	/**
	 * Project name field in *Experience → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_block.items[].projectName
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	projectName: prismic.KeyTextField;
	
	/**
	 * Project link field in *Experience → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_block.items[].projectLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	projectLink: prismic.LinkField;
	
	/**
	 * Project description field in *Experience → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: experience_block.items[].projectDescription
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	projectDescription: prismic.RichTextField;
}

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ExperienceBlockSliceDefaultPrimary>, Simplify<ExperienceBlockSliceDefaultItem>>;

/**
 * Slice variation for *Experience*
 */
type ExperienceBlockSliceVariation = ExperienceBlockSliceDefault

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience_block`
 * - **Description**: ExperienceBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceBlockSlice = prismic.SharedSlice<"experience_block", ExperienceBlockSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroBlockSliceDefaultPrimary {
	/**
	 * Front-side image field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_block.primary.frontSideImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	frontSideImage: prismic.ImageField<never>;
	
	/**
	 * Back-side image field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_block.primary.backSideImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	backSideImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroBlockSliceVariation = HeroBlockSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_block`
 * - **Description**: HeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSlice = prismic.SharedSlice<"hero_block", HeroBlockSliceVariation>;

/**
 * Primary content in *ImageGrid → Primary*
 */
export interface ImageGridBlockSliceDefaultPrimary {
	/**
	 * Spacing top field in *ImageGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: image_grid_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *ImageGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: image_grid_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Size field in *ImageGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1
	 * - **API ID Path**: image_grid_block.primary.size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	size: prismic.SelectField<"1" | "2", "filled">;
}

/**
 * Primary content in *ImageGrid → Items*
 */
export interface ImageGridBlockSliceDefaultItem {
	/**
	 * Image field in *ImageGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_grid_block.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Caption field in *ImageGrid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_grid_block.items[].caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	caption: prismic.RichTextField;
	
	/**
	 * Caption align field in *ImageGrid → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left
	 * - **API ID Path**: image_grid_block.items[].captionAlign
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	captionAlign: prismic.SelectField<"left" | "center", "filled">;
	
	/**
	 * Parallax mode field in *ImageGrid → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: image_grid_block.items[].parallaxMode
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	parallaxMode: prismic.BooleanField;
	
	/**
	 * Display mode field in *ImageGrid → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: auto
	 * - **API ID Path**: image_grid_block.items[].displayMode
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	displayMode: prismic.SelectField<"auto" | "square", "filled">;
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ImageGridBlockSliceDefaultPrimary>, Simplify<ImageGridBlockSliceDefaultItem>>;

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridBlockSliceVariation = ImageGridBlockSliceDefault

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid_block`
 * - **Description**: ImageGridBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridBlockSlice = prismic.SharedSlice<"image_grid_block", ImageGridBlockSliceVariation>;

/**
 * Primary content in *IntroText → Primary*
 */
export interface IntroTextBlockSliceDefaultPrimary {
	/**
	 * Title field in *IntroText → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: intro_text_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Title size field in *IntroText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 2
	 * - **API ID Path**: intro_text_block.primary.titleSize
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	titleSize: prismic.SelectField<"2" | "3" | "4" | "5" | "6", "filled">;
	
	/**
	 * Text field in *IntroText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: intro_text_block.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
	
	/**
	 * Large text field in *IntroText → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: intro_text_block.primary.largeText
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	largeText: prismic.BooleanField;
	
	/**
	 * Spacing top field in *IntroText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: intro_text_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *IntroText → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: intro_text_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
}

/**
 * Default variation for IntroText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<IntroTextBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *IntroText*
 */
type IntroTextBlockSliceVariation = IntroTextBlockSliceDefault

/**
 * IntroText Shared Slice
 *
 * - **API ID**: `intro_text_block`
 * - **Description**: IntroTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextBlockSlice = prismic.SharedSlice<"intro_text_block", IntroTextBlockSliceVariation>;

/**
 * Primary content in *Marquee → Primary*
 */
export interface MarqueeBlockSliceDefaultPrimary {
	/**
	 * Spacing top field in *Marquee → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: marquee_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *Marquee → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: marquee_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Double marquee field in *Marquee → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: marquee_block.primary.doubleMarquee
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doubleMarquee: prismic.BooleanField;
	
	/**
	 * Speed (main) field in *Marquee → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_block.primary.speedMain
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	speedMain: prismic.NumberField;
	
	/**
	 * Speed (secondary) field in *Marquee → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_block.primary.speedSecondary
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	speedSecondary: prismic.NumberField;
	
	/**
	 * Start offset (main) field in *Marquee → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_block.primary.startOffsetMain
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	startOffsetMain: prismic.NumberField;
	
	/**
	 * Start offset (secondary) field in *Marquee → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_block.primary.startOffsetSecondary
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	startOffsetSecondary: prismic.NumberField;
}

/**
 * Primary content in *Marquee → Items*
 */
export interface MarqueeBlockSliceDefaultItem {
	/**
	 * Text item field in *Marquee → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_block.items[].textItem
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	textItem: prismic.RichTextField;
	
	/**
	 * Divider field in *Marquee → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_block.items[].divider
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	divider: prismic.KeyTextField;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MarqueeBlockSliceDefaultPrimary>, Simplify<MarqueeBlockSliceDefaultItem>>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeBlockSliceVariation = MarqueeBlockSliceDefault

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee_block`
 * - **Description**: MarqueeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeBlockSlice = prismic.SharedSlice<"marquee_block", MarqueeBlockSliceVariation>;

/**
 * Primary content in *NewsFeed → Primary*
 */
export interface NewsFeedBlockSliceDefaultPrimary {
	/**
	 * Title field in *NewsFeed → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_feed_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * News feed field in *NewsFeed → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_feed_block.primary.newsFeed
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	newsFeed: prismic.ContentRelationshipField<"newsFeed">;
	
	/**
	 * Spacing top field in *NewsFeed → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: news_feed_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *NewsFeed → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: news_feed_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Container size field in *NewsFeed → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1
	 * - **API ID Path**: news_feed_block.primary.containerSize
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	containerSize: prismic.SelectField<"1" | "2", "filled">;
}

/**
 * Default variation for NewsFeed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsFeedBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<NewsFeedBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *NewsFeed*
 */
type NewsFeedBlockSliceVariation = NewsFeedBlockSliceDefault

/**
 * NewsFeed Shared Slice
 *
 * - **API ID**: `news_feed_block`
 * - **Description**: NewsFeedBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsFeedBlockSlice = prismic.SharedSlice<"news_feed_block", NewsFeedBlockSliceVariation>;

/**
 * Primary content in *PageTop → Primary*
 */
export interface PageTopBlockSliceDefaultPrimary {
	/**
	 * Title field in *PageTop → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_top_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *PageTop → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_top_block.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Icon field in *PageTop → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: page_top_block.primary.icon
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	icon: prismic.SelectField<"none" | "handLoveYou" | "handsHeart", "filled">;
}

/**
 * Default variation for PageTop Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageTopBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PageTopBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *PageTop*
 */
type PageTopBlockSliceVariation = PageTopBlockSliceDefault

/**
 * PageTop Shared Slice
 *
 * - **API ID**: `page_top_block`
 * - **Description**: PageTopBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageTopBlockSlice = prismic.SharedSlice<"page_top_block", PageTopBlockSliceVariation>;

/**
 * Primary content in *RecentCases → Primary*
 */
export interface RecentCasesBlockSliceDefaultPrimary {
	/**
	 * Title field in *RecentCases → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_cases_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *RecentCases → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_cases_block.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Spacing top field in *RecentCases → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: recent_cases_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *RecentCases → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: recent_cases_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
}

/**
 * Primary content in *RecentCases → Items*
 */
export interface RecentCasesBlockSliceDefaultItem {
	/**
	 * Case field in *RecentCases → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_cases_block.items[].case
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	case: prismic.ContentRelationshipField<"case">;
}

/**
 * Default variation for RecentCases Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentCasesBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<RecentCasesBlockSliceDefaultPrimary>, Simplify<RecentCasesBlockSliceDefaultItem>>;

/**
 * Slice variation for *RecentCases*
 */
type RecentCasesBlockSliceVariation = RecentCasesBlockSliceDefault

/**
 * RecentCases Shared Slice
 *
 * - **API ID**: `recent_cases_block`
 * - **Description**: RecentCasesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentCasesBlockSlice = prismic.SharedSlice<"recent_cases_block", RecentCasesBlockSliceVariation>;

/**
 * Primary content in *SingleImage → Primary*
 */
export interface SingleImageBlockSliceDefaultPrimary {
	/**
	 * Image field in *SingleImage → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: single_image_block.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Caption field in *SingleImage → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: single_image_block.primary.caption
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	caption: prismic.RichTextField;
	
	/**
	 * Display mode field in *SingleImage → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: auto
	 * - **API ID Path**: single_image_block.primary.displayMode
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	displayMode: prismic.SelectField<"auto" | "square" | "cover", "filled">;
	
	/**
	 * Parallax mode field in *SingleImage → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: single_image_block.primary.parallaxMode
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	parallaxMode: prismic.BooleanField;
	
	/**
	 * Spacing top field in *SingleImage → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: single_image_block.primary.spacingTop
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingTop: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
	
	/**
	 * Spacing bottom field in *SingleImage → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 0
	 * - **API ID Path**: single_image_block.primary.spacingBottom
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	spacingBottom: prismic.SelectField<"0" | "1" | "2" | "3", "filled">;
}

/**
 * Default variation for SingleImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleImageBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<SingleImageBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *SingleImage*
 */
type SingleImageBlockSliceVariation = SingleImageBlockSliceDefault

/**
 * SingleImage Shared Slice
 *
 * - **API ID**: `single_image_block`
 * - **Description**: SingleImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleImageBlockSlice = prismic.SharedSlice<"single_image_block", SingleImageBlockSliceVariation>;

/**
 * Primary content in *WorksGallery → Primary*
 */
export interface WorksGalleryBlockSliceDefaultPrimary {
	/**
	 * Gallery field in *WorksGallery → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: works_gallery_block.primary.gallery
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	gallery: prismic.ContentRelationshipField<"worksGallery">;
}

/**
 * Default variation for WorksGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksGalleryBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<WorksGalleryBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *WorksGallery*
 */
type WorksGalleryBlockSliceVariation = WorksGalleryBlockSliceDefault

/**
 * WorksGallery Shared Slice
 *
 * - **API ID**: `works_gallery_block`
 * - **Description**: WorksGalleryBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksGalleryBlockSlice = prismic.SharedSlice<"works_gallery_block", WorksGalleryBlockSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			AboutDocument,
			AboutDocumentData,
			AboutDocumentDataSlicesSlice,
			CaseDocument,
			CaseDocumentData,
			CaseDocumentDataSlicesSlice,
			ContactDocument,
			ContactDocumentData,
			ContactDocumentDataSlicesSlice,
			ContactEmailDocument,
			ContactEmailDocumentData,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			NewsFeedDocument,
			NewsFeedDocumentData,
			NewsFeedDocumentDataNewsItem,
			NewsPostDocument,
			NewsPostDocumentData,
			SiteFooterDocument,
			SiteFooterDocumentData,
			SiteFooterDocumentDataSlicesSlice,
			SiteHeaderDocument,
			SiteHeaderDocumentData,
			SiteInformationDocument,
			SiteInformationDocumentData,
			SiteNavigationDocument,
			SiteNavigationDocumentData,
			SiteNavigationDocumentDataNavLinksItem,
			SocialAccountDocument,
			SocialAccountDocumentData,
			SocialLinksDocument,
			SocialLinksDocumentData,
			SocialLinksDocumentDataSocialLinksItem,
			WorkDocument,
			WorkDocumentData,
			WorkDocumentDataSlicesSlice,
			WorksGalleryDocument,
			WorksGalleryDocumentData,
			WorksGalleryDocumentDataImagesItem,
			AllDocumentTypes,
			AllCasesBlockSlice,
			AllCasesBlockSliceDefaultPrimary,
			AllCasesBlockSliceVariation,
			AllCasesBlockSliceDefault,
			BasicTextBlockSlice,
			BasicTextBlockSliceDefaultPrimary,
			BasicTextBlockSliceVariation,
			BasicTextBlockSliceDefault,
			CasePageTopBlockSlice,
			CasePageTopBlockSliceDefaultPrimary,
			CasePageTopBlockSliceVariation,
			CasePageTopBlockSliceDefault,
			ContactsBlockSlice,
			ContactsBlockSliceDefaultPrimary,
			ContactsBlockSliceVariation,
			ContactsBlockSliceDefault,
			ExperienceBlockSlice,
			ExperienceBlockSliceDefaultPrimary,
			ExperienceBlockSliceDefaultItem,
			ExperienceBlockSliceVariation,
			ExperienceBlockSliceDefault,
			HeroBlockSlice,
			HeroBlockSliceDefaultPrimary,
			HeroBlockSliceVariation,
			HeroBlockSliceDefault,
			ImageGridBlockSlice,
			ImageGridBlockSliceDefaultPrimary,
			ImageGridBlockSliceDefaultItem,
			ImageGridBlockSliceVariation,
			ImageGridBlockSliceDefault,
			IntroTextBlockSlice,
			IntroTextBlockSliceDefaultPrimary,
			IntroTextBlockSliceVariation,
			IntroTextBlockSliceDefault,
			MarqueeBlockSlice,
			MarqueeBlockSliceDefaultPrimary,
			MarqueeBlockSliceDefaultItem,
			MarqueeBlockSliceVariation,
			MarqueeBlockSliceDefault,
			NewsFeedBlockSlice,
			NewsFeedBlockSliceDefaultPrimary,
			NewsFeedBlockSliceVariation,
			NewsFeedBlockSliceDefault,
			PageTopBlockSlice,
			PageTopBlockSliceDefaultPrimary,
			PageTopBlockSliceVariation,
			PageTopBlockSliceDefault,
			RecentCasesBlockSlice,
			RecentCasesBlockSliceDefaultPrimary,
			RecentCasesBlockSliceDefaultItem,
			RecentCasesBlockSliceVariation,
			RecentCasesBlockSliceDefault,
			SingleImageBlockSlice,
			SingleImageBlockSliceDefaultPrimary,
			SingleImageBlockSliceVariation,
			SingleImageBlockSliceDefault,
			WorksGalleryBlockSlice,
			WorksGalleryBlockSliceDefaultPrimary,
			WorksGalleryBlockSliceVariation,
			WorksGalleryBlockSliceDefault
		}
	}
}