// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  all_cases_block: dynamic(() => import('./AllCases')),
  basic_text_block: dynamic(() => import('./BasicText')),
  case_page_top_block: dynamic(() => import('./CasePageTop')),
  contacts_block: dynamic(() => import('./Contacts')),
  experience_block: dynamic(() => import('./Experience')),
  hero_block: dynamic(() => import('./Hero')),
  image_grid_block: dynamic(() => import('./ImageGrid')),
  intro_text_block: dynamic(() => import('./IntroText')),
  marquee_block: dynamic(() => import('./Marquee')),
  news_feed_block: dynamic(() => import('./NewsFeed')),
  page_top_block: dynamic(() => import('./PageTop')),
  recent_cases_block: dynamic(() => import('./RecentCases')),
  single_image_block: dynamic(() => import('./SingleImage')),
  works_gallery_block: dynamic(() => import('./WorksGallery')),
};
